### PR TITLE
V1.3.18

### PR DESCRIPTION
**Pull request by ggentzel**

### CODE REVIEW

**Review by arm22 — APPROVED** [review]
Nice work!

**Comment by arm22** [comment]
It looks like the CI stuff has been broken for a while, @DNewk or @syagolnikov do you know how we can fix that?

**Comment by arm22** [comment]
> It looks like the CI stuff has been broken for a while, @DNewk or @syagolnikov do you know how we can fix that?

Looking at the errors in Travis it's failing to run the tests, maybe something we can look into as devs.

**Review by rmomii — APPROVED** [review]
merge it!

**Pull request merged**
