### PR TITLE
Claim.allClaimsForClient

### PR DESCRIPTION
**Pull request by privard**
- Added method to claim module to retrieve all claims for a given client
- Added unit tests for claim module
- Fixed linter problems on campaign file

### CODE REVIEW

**Review by ggentzel — APPROVED** [review]
Looks good

**Review by sspencer — COMMENTED** [review]
Is the format of clientId being validated before insertion into the pathname template on line 95?

**Comment by privard** [comment]
There's wasn't any format validation on allClaims so I didn't do any. Plus, I think the template literal is going to toString anything that comes in, so worst case, an invalid format will produce a 404 on the claim side. Not sure it's worth the extra validation. Thoughts?

**Comment by privard** [comment]
@brozeph I will let you merge this once you are satisfied.

**Review by brozeph — APPROVED** [review]
Looks good!

**Pull request merged**
